# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ICLExact <- function(adj, z, verbose) {
    .Call('GreedySBTM_cpp_ICLExact', PACKAGE = 'GreedySBTM', adj, z, verbose)
}

cpp_GreedyICL <- function(adj, z, max_n_iter, verbose) {
    .Call('GreedySBTM_cpp_GreedyICL', PACKAGE = 'GreedySBTM', adj, z, max_n_iter, verbose)
}

cpp_GreedyMerge <- function(adj, z, verbose) {
    .Call('GreedySBTM_cpp_GreedyMerge', PACKAGE = 'GreedySBTM', adj, z, verbose)
}

cpp_CollapseLabels <- function(vec) {
    .Call('GreedySBTM_cpp_CollapseLabels', PACKAGE = 'GreedySBTM', vec)
}

